name: photocollage

services:
  photocollage-web:
    image: ${DOCKER_REGISTRY-}photocollageweb
    container_name: photocollage-web
    build:
      context: .
      dockerfile: PhotoCollage.Web/Dockerfile
    restart: unless-stopped
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://photocollage-dashboard:18889
    volumes:
      - s:/screensaver:/data/collage:ro
    depends_on:
      - photocollage-db
      - photocollage-dashboard

  photocollage-db:
    image: postgres:latest
    container_name: photocollage-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      - POSTGRES_DB=photocollage
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Ch@ng3M3

  photocollage-db-admin:
    image: dpage/pgadmin4:latest
    container_name: photocollage-db-admin
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@pgadmin.com
      - PGADMIN_DEFAULT_PASSWORD=Ch@ng3M3
      - PGADMIN_LISTEN_PORT=80
    ports:
      - 15432:80
    depends_on:
      - photocollage-db

  photocollage-dashboard:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:latest
    container_name: photocollage-dashboard
    restart: unless-stopped
    ports:
      - 18888:18888
